import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { store } from "../redux/store";
import Providers from "../redux/provider";
export const metadata = {
  title: "Proof app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={`${inter.className} bg-black pt-20`}>
        <Providers>
        <nav className="border-b border-green-800 pt-5 pb-5 flex absolute top-0 w-full items-center justify-evenly">
            <button>
              {" "}
              <Link href="/" className="text-white hover:text-yellow-200 ">
                Home
              </Link>
            </button>
            <button>
              <Link
                href="/aboutUs"
                className="text-white hover:text-yellow-200"
              >
                About us
              </Link>
            </button>
            <button>
              <Link
                href="/pruebaDaniel"
                className="text-white hover:text-yellow-200"
              >
                Prueba Daniel
              </Link>
            </button>
            <button>
              <Link
                href="/pruebaMauroo"
                className="text-white hover:text-yellow-200"
              >
                Prueba Mauroo
              </Link>
            </button>
          </nav>
          { children }
        </Providers>
       
      </body>

    </html>

  );
}
